# Generated by Django 4.0.5 on 2023-02-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_provider',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='services.serviceprovider'),
            preserve_default=False,
        ),
    ]
