# Generated by Django 4.0.5 on 2023-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='service_provider_id',
            field=models.IntegerField(null=True),
        ),
    ]
