# Generated by Django 4.0.5 on 2023-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='star',
            field=models.IntegerField(null=True),
        ),
    ]
