# Generated by Django 4.1.6 on 2023-02-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
